# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Havendaxa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Havendaxa
pod 'Toast-Swift'
pod 'SVPinView'
pod 'SVProgressHUD'
#pod 'Charts'
pod 'ObjectMapper'
pod 'Alamofire'

end
